name: Docker image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        name: Check out code
      - uses: mr-smithers-excellent/docker-build-push@v6
        name: Build & push Docker image
        with:
          image: hello-world-ghcr
          registry: ghcr.io
          username: baji-myrtle
          password: ${{ secrets.GH_PAT }}
